[tool.poetry]
name = "start-kinesis-app"
version = "0.1.0"
description = ""
authors = ["Raphael Eymann <raphael.eymann@amanox.ch>"]

[tool.poetry.dependencies]
python = "^3.9"
crhelper = "^2.0.11"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
